### ISSUE TITLE
[TODO] isLoser() - Chomp

### ISSUE THREAD

**Issue by uyennhiquang** [uyennhiquang/chomp-java#5]
A method that determines whether the current player is the loser. It might be used by chomp() to update the game's status, or it itself can be the status updater. The current player is the loser when the only tile they can bite is the top left one, meaning the number of tiles that have been bitten is number_of_tiles == rows * cols - 1.

**Comment by kcl2154** [comment]
benjamin danklin

**Comment by uyennhiquang** [comment]
Removed due to being unneeded.
